doctrine:
  dbal:
    types:
      account_id: 'App\Account\Infrastructure\Persistence\Doctrine\Type\IdType'
      account_money: 'App\Account\Infrastructure\Persistence\Doctrine\Type\MoneyType'
  orm:
    mappings:
      Account:
        type: 'xml'
        dir: '%kernel.project_dir%/src/Account/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: 'App\Account\Domain'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
