framework:
  messenger:
    transports:
      commands:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: App\Messenger\Service\JsonMessengerSerializer
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0
        options:
          exchange:
            name: commands
            type: direct
            default_publish_routing_key: command
          queues:
            commands:
              binding_keys: [command]
      events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: App\Messenger\Service\JsonMessengerSerializer
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0
        options:
          exchange:
            name: events
            type: fanout
          queues:
            events: ~

    routing:
      # Route your messages to the transports
      App\Messenger\Messages\Message: events
